"""
graft_dgraphfin.py
──────────────────
DGraphFin is a financial transaction graph from Alipay.
Its entity IDs have NO overlap with IEEE-CIS.

Two-stage graft:
  Stage A — Pre-training:
    Train GraphSAGE / HGT on DGraphFin's labeled graph.
    Save weights. These capture what "fraud neighborhood structure"
    looks like in a real financial graph.

  Stage B — Weight transfer + feature transfer:
    Initialize the IEEE-CIS GNN (Model E) with DGraphFin weights.
    Also use the pre-computed columns (shared_infrastructure_count,
    2nd_degree_fraud_rate, gnn_node_embedding, graph_risk_score)
    that were generated by running DGraphFin's GNN on IEEE-CIS users.
    These are already in the schema — we parse and validate them here.
"""

import json
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from pathlib import Path
from typing import Optional, Dict
import sys
sys.path.append(str(Path(__file__).parent.parent))
from utils.constants import GNN_EMBED_DIM


# ─────────────────────────────────────────────────────────────────────────────
# STAGE A: DGRAPHFIN PRE-TRAINING
# ─────────────────────────────────────────────────────────────────────────────

class GraphSAGELayer(nn.Module):
    """
    Single GraphSAGE aggregation layer.
    Aggregates neighbor features via mean pooling, then concatenates
    with self features and projects.
    """
    def __init__(self, in_dim: int, out_dim: int, dropout: float = 0.2):
        super().__init__()
        self.linear = nn.Linear(in_dim * 2, out_dim)
        self.dropout = nn.Dropout(dropout)
        self.norm = nn.LayerNorm(out_dim)

    def forward(self, x: torch.Tensor, adj: torch.Tensor) -> torch.Tensor:
        """
        x   : [N, in_dim]  node features
        adj : [N, N] or sparse adjacency (row-normalised)
        """
        # Aggregate neighbor features (mean)
        agg = torch.mm(adj, x)                     # [N, in_dim]
        combined = torch.cat([x, agg], dim=-1)     # [N, 2*in_dim]
        out = self.linear(combined)                 # [N, out_dim]
        out = self.norm(F.relu(out))
        out = self.dropout(out)
        return out


class DGraphFinGNN(nn.Module):
    """
    3-layer GraphSAGE for DGraphFin pre-training.
    Input features: DGraphFin provides 17 node features per node.
    Output: 128-dim embedding + binary fraud classification head.

    This same architecture (without the classification head) is
    used as Model E's encoder backbone after weight transfer.
    """
    DGRAPHFIN_FEAT_DIM = 17   # DGraphFin node feature dimension

    def __init__(
        self,
        in_dim:    int = 17,
        hidden:    int = 256,
        embed_dim: int = GNN_EMBED_DIM,  # 128
        dropout:   float = 0.2
    ):
        super().__init__()
        self.layer1 = GraphSAGELayer(in_dim,    hidden,    dropout)
        self.layer2 = GraphSAGELayer(hidden,    hidden,    dropout)
        self.layer3 = GraphSAGELayer(hidden,    embed_dim, dropout)
        self.classifier = nn.Linear(embed_dim, 2)   # fraud / legitimate

    def encode(self, x: torch.Tensor, adj: torch.Tensor) -> torch.Tensor:
        """Returns node embeddings (no classification head)."""
        h = self.layer1(x, adj)
        h = self.layer2(h, adj)
        h = self.layer3(h, adj)
        return h   # [N, 128]

    def forward(
        self, x: torch.Tensor, adj: torch.Tensor
    ) -> Dict[str, torch.Tensor]:
        emb = self.encode(x, adj)
        logits = self.classifier(emb)
        return {"embedding": emb, "logits": logits}


def load_dgraphfin(dgraphfin_dir: str):
    """
    Load DGraphFin dataset.
    Expected files: x.pt (node features), y.pt (labels), edge_index.pt
    Or: dgraphfin.npz with keys x, y, edge_index.

    DGraphFin labels: 0=legitimate, 1=fraud, 2=unlabeled
    We use only labeled nodes (label in {0,1}) for supervised pre-training.
    """
    dpath = Path(dgraphfin_dir)

    if (dpath / "dgraphfin.npz").exists():
        data = np.load(dpath / "dgraphfin.npz")
        x          = torch.tensor(data["x"],          dtype=torch.float32)
        y          = torch.tensor(data["y"],          dtype=torch.long).squeeze()
        edge_index = torch.tensor(data["edge_index"], dtype=torch.long)
    else:
        x          = torch.load(dpath / "x.pt")
        y          = torch.load(dpath / "y.pt").squeeze()
        edge_index = torch.load(dpath / "edge_index.pt")

    print(f"[DGraphFin] Loaded data: x={x.shape}, y={y.shape}, edge_index={edge_index.shape}")

    if edge_index.shape[1] == 2 and edge_index.shape[0] != 2:
        edge_index = edge_index.t().contiguous()

    N = x.shape[0]

    # Build sparse row-normalised adjacency (add self-loops)
    row, col = edge_index
    # Self-loops
    self_loop = torch.arange(N)
    row = torch.cat([row, self_loop])
    col = torch.cat([col, self_loop])

    # Row-normalise: D^{-1} A
    deg = torch.zeros(N)
    deg.scatter_add_(0, row, torch.ones(row.shape[0]))
    norm = 1.0 / deg.clamp(min=1.0)
    vals = norm[row]

    adj = torch.sparse_coo_tensor(
        torch.stack([row, col]), vals, size=(N, N)
    ).coalesce()

    # Labeled mask (exclude class 2 = unlabeled)
    labeled_mask = (y == 0) | (y == 1)

    labeled_indices = torch.where(labeled_mask)[0]
# 2. Sample a manageable subset (e.g., 100k nodes)
    # This reduces the initial 3.7M rows down to a size your RAM can handle
    subset_size = 100000 
    perm = torch.randperm(len(labeled_indices))[:subset_size]
    keep_nodes = labeled_indices[perm]

    # 3. Filter the features and labels
    x_sub = x[keep_nodes]
    y_sub = y[keep_nodes]

    # 4. Re-index edges to form a subgraph
    # We only keep edges where BOTH nodes are in our sample
    mask_edges = torch.isin(edge_index[0], keep_nodes) & torch.isin(edge_index[1], keep_nodes)
    edge_sub = edge_index[:, mask_edges]
    
    # Map old IDs to new IDs (0 to subset_size-1)
    node_idx_map = {old_id.item(): new_id for new_id, old_id in enumerate(keep_nodes)}
    
    # Update edge indices to the new 0-100,000 range
    new_row = torch.tensor([node_idx_map[i.item()] for i in edge_sub[0]], dtype=torch.long)
    new_col = torch.tensor([node_idx_map[i.item()] for i in edge_sub[1]], dtype=torch.long)

    # 5. Build the small Adjacency Matrix
    N_sub = x_sub.shape[0]
    self_loop = torch.arange(N_sub)
    row = torch.cat([new_row, self_loop])
    col = torch.cat([new_col, self_loop])

    deg = torch.zeros(N_sub)
    deg.scatter_add_(0, row, torch.ones(row.shape[0]))
    norm = 1.0 / deg.clamp(min=1.0)
    vals = norm[row]

    adj_sub = torch.sparse_coo_tensor(
        torch.stack([row, col]), vals, size=(N_sub, N_sub)
    ).coalesce()

    # Now we return a mask that is all True, because we already filtered the data
    new_mask = torch.ones(N_sub, dtype=torch.bool)

    print(f"[DGraphFin] Subgraph created: {N_sub:,} nodes | {edge_sub.shape[1]:,} edges")
    return x_sub, y_sub, adj_sub, new_mask


def pretrain_dgraphfin(
    dgraphfin_dir: str,
    save_path:     str,
    epochs:        int = 100,
    lr:            float = 1e-3,
    device:        str = "cpu"
) -> DGraphFinGNN:
    """
    Pre-train GraphSAGE on DGraphFin's labeled fraud graph.
    Uses focal loss (gamma=2) because DGraphFin is severely imbalanced
    (~1.5% fraud rate).

    Saves full model weights to save_path.
    Returns trained model.
    """
    x, y, adj, mask = load_dgraphfin(dgraphfin_dir)
    dev = torch.device(device)
    x, y, adj = x.to(dev), y.to(dev), adj.to(dev)

    model = DGraphFinGNN(in_dim=x.shape[1]).to(dev)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=5e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)

    # Focal loss for class imbalance
    def focal_loss(logits, labels, gamma=2.0):
        ce = F.cross_entropy(logits, labels, reduction="none")
        pt = torch.exp(-ce)
        return ((1 - pt) ** gamma * ce).mean()

    best_val_auc = 0
    labeled_idx  = mask.nonzero(as_tuple=True)[0]
    n_train      = int(0.7 * len(labeled_idx))
    train_idx    = labeled_idx[:n_train]
    val_idx      = labeled_idx[n_train:]

    for epoch in range(1, epochs + 1):
        model.train()
        optimizer.zero_grad()
        out    = model(x, adj)
        loss   = focal_loss(out["logits"][train_idx], y[train_idx])
        loss.backward()
        optimizer.step()
        scheduler.step()

        if epoch % 10 == 0:
            model.eval()
            with torch.no_grad():
                val_logits = model(x, adj)["logits"][val_idx]
                val_probs  = F.softmax(val_logits, dim=-1)[:, 1].cpu().numpy()
                val_labels = y[val_idx].cpu().numpy()
            from sklearn.metrics import roc_auc_score
            try:
                auc = roc_auc_score(val_labels, val_probs)
            except Exception:
                auc = 0.5
            print(f"  Epoch {epoch:3d} | loss={loss.item():.4f} | val_AUC={auc:.4f}")
            if auc > best_val_auc:
                best_val_auc = auc
                torch.save(model.state_dict(), save_path)

    print(f"[DGraphFin] Pre-training done. Best val AUC: {best_val_auc:.4f}")
    print(f"[DGraphFin] Weights saved to {save_path}")
    return model


# ─────────────────────────────────────────────────────────────────────────────
# STAGE B: VALIDATE & NORMALISE PRE-COMPUTED COLUMNS
# ─────────────────────────────────────────────────────────────────────────────

def validate_graph_cols(ieee_df: pd.DataFrame) -> pd.DataFrame:
    """
    The schema already contains pre-computed DGraphFin-derived columns:
      shared_infrastructure_count  — number of users sharing same IP/device
      2nd_degree_fraud_rate        — fraud rate in 2-hop neighborhood
      gnn_node_embedding           — already parsed in graft_ieee_cis
      graph_risk_score             — scalar summarising graph risk

    This function validates ranges, fills missing values with safe defaults,
    and adds derived interaction features.
    """
    # shared_infrastructure_count: int, clip to [0, 100]
    if "shared_infrastructure_count" in ieee_df.columns:
        ieee_df["shared_infrastructure_count"] = (
            ieee_df["shared_infrastructure_count"]
            .fillna(0).clip(0, 100).astype(np.int32)
        )
    else:
        ieee_df["shared_infrastructure_count"] = 0

    # 2nd_degree_fraud_rate: float in [0, 1]
    if "2nd_degree_fraud_rate" in ieee_df.columns:
        ieee_df["2nd_degree_fraud_rate"] = (
            ieee_df["2nd_degree_fraud_rate"]
            .fillna(0.0).clip(0.0, 1.0).astype(np.float32)
        )
    else:
        ieee_df["2nd_degree_fraud_rate"] = 0.0

    # graph_risk_score: float, usually [0,1] but normalise to be safe
    if "graph_risk_score" in ieee_df.columns:
        grs = ieee_df["graph_risk_score"].fillna(0.0)
        mn, mx = grs.min(), grs.max()
        ieee_df["graph_risk_score"] = ((grs - mn) / max(mx - mn, 1e-9)).astype(np.float32)
    else:
        ieee_df["graph_risk_score"] = 0.0

    # ── Derived interaction features ──
    # High shared infra AND high 2nd-degree fraud = strong ring signal
    ieee_df["ring_signal"] = (
        ieee_df["shared_infrastructure_count"].clip(0,10) / 10.0 *
        ieee_df["2nd_degree_fraud_rate"]
    ).astype(np.float32)

    # Combinatorial: high graph risk AND high transaction amount = escalated risk
    ieee_df["graph_amt_risk"] = (
        ieee_df["graph_risk_score"] *
        np.log1p(ieee_df["TransactionAmt"].fillna(0))
    ).astype(np.float32)

    print("[DGraphFin] Graph columns validated and interaction features added")
    return ieee_df


def get_transfer_weights(pretrained_path: str) -> Dict[str, torch.Tensor]:
    """
    Load the pre-trained DGraphFin weights.
    Strip the classification head — only encoder layers transfer.
    Called by Model E (HeteroGNN) during __init__ to initialise its
    shared encoder backbone.
    """
    state_dict = torch.load(pretrained_path, map_location="cpu")
    # Keep only layer1, layer2, layer3 weights (not classifier)
    encoder_weights = {
        k: v for k, v in state_dict.items()
        if not k.startswith("classifier")
    }
    print(f"[DGraphFin] Transfer weights loaded: {len(encoder_weights)} parameter tensors")
    return encoder_weights


if __name__ == "__main__":
    # Stage A: Pre-train (run once, takes ~10 min on CPU, ~2 min on GPU)
    pretrain_dgraphfin(
        dgraphfin_dir="data/dgraphfin/",
        save_path="models/dgraphfin_pretrained.pt",
        epochs=100,
        device="cuda" if torch.cuda.is_available() else "cpu"
    )

    # Stage B: Validate columns on processed IEEE-CIS
    ieee_df = pd.read_parquet("data/processed/ieee_cis_processed.parquet")
    ieee_df = validate_graph_cols(ieee_df)
    ieee_df.to_parquet("data/processed/ieee_cis_with_graph.parquet", index=False)
    print(ieee_df[["shared_infrastructure_count","2nd_degree_fraud_rate",
                   "graph_risk_score","ring_signal"]].describe())
